import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import { cookies } from "next/headers";
import "./globals.css";
import ThemeToggle from "@/components/ThemeToggle";
import { coerceMode, THEME_COOKIE } from "@/lib/theme";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const cookieStore = await cookies();
  const mode = coerceMode(cookieStore.get(THEME_COOKIE)?.value ?? null);

  return (
    <html lang="en" data-theme={mode}>
      <body className={`${geistSans.variable} ${geistMono.variable}`}>
        <header style={{display:'flex',justifyContent:'space-between',alignItems:'center',padding:'12px 20px'}}>
          <a href="/" aria-label="Home" style={{textDecoration:'none',color:'inherit',fontWeight:600}}>Fonts App</a>
          <ThemeToggle initial={mode} />
        </header>
        {children}
      </body>
    </html>
  );
}
